# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  username: myapp
  password: password
  database: myappdev
  host: localhost
  #pool: 5
  #timeout: 5000

test:
    adapter: postgresql
    username: myapp
    password: password
    database: myapptest
  #pool: 5
  #timeout: 5000

production:
  adapter: postgresql
  database: lqwfwakxzf
  username: lqwfwakxzf
  password: dDDCa5DVqJsvHgfBIpZi
  host: ec2-107-21-110-75.compute-1.amazonaws.com
  encoding: unicode
  port: 5432
  pool: 5
  timeout: 5000
